version: "3.9"

services:
  db:
    build:
      context: .
      dockerfile: deployment/docker-images/auth-service/postgres.Dockerfile
    container_name: auth-service-db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 30s
      timeout: 5s
      retries: 5
  # redis:
  #   image: redis:7.4.1-alpine
  #   container_name: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "redis-cli ping"]
  #     interval: 30s
  #     timeout: 5s
  #     retries: 5

volumes:
  db-data:
  redis-data:
